project:
  type: website
  output-dir: docs

website:
  title: "Nipun Batra"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: papers
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: group.qmd
        text: Group
      - href: blog
        text: Blog
      - href: news.qmd
        text: News
      - href: media.qmd
        text: Media
      - href: files/cv.pdf
        text: CV

format:
  html:
    theme:
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto

